// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TeslaML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public string Id { get; set; }


        [ColumnName("Sentiment"), LoadColumn(1)]
        public bool Sentiment { get; set; }


        [ColumnName("SentimentText"), LoadColumn(2)]
        public string SentimentText { get; set; }


    }
}
